#!/bin/bash
# Training Data Hızlı Başlangıç Scripti

echo "======================================================================"
echo "🚀 TRAINING DATA HIZLI BAŞLANGIÇ"
echo "======================================================================"
echo ""

# Renk kodları
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}Bu script size görüntü toplama konusunda yardımcı olacak.${NC}"
echo ""

# Kullanıcıya seçenek sun
echo "Hangi yöntemi tercih edersiniz?"
echo ""
echo "1) Manuel indirme (ÖNERİLEN - Kolay ve hızlı)"
echo "2) Kendi fotoğraflarımı çekeceğim"
echo "3) İki yöntemi birleştireceğim"
echo "4) İpuçları göster ve çık"
echo ""
read -p "Seçiminiz (1-4): " choice

case $choice in
    1)
        echo ""
        echo -e "${GREEN}✅ Manuel İndirme - Adım Adım Rehber${NC}"
        echo "======================================================================"
        echo ""
        echo "📋 İLK HEDEF: 3 parça için 10'ar görüntü (toplam 30)"
        echo ""
        echo -e "${YELLOW}ADIM 1: VIDA (Bolt/Screw)${NC}"
        echo "----------------------------------------------------------------------"
        echo "1. Google'ı açın: https://www.google.com/imghp"
        echo "2. Şu terimleri sırayla arayın:"
        echo "   - 'hex bolt'"
        echo "   - 'machine screw'"
        echo "   - 'M8 bolt'"
        echo "3. Her aramadan 3-4 görüntü indirin (Sağ tık → Resmi farklı kaydet)"
        echo "4. Dosyaları şuraya kaydedin: training_data/vida/"
        echo "   Dosya adları: vida_01.jpg, vida_02.jpg, ... vida_10.jpg"
        echo ""
        echo "✅ İndirdiğinizde buraya dönün ve ENTER'a basın..."
        read
        
        echo ""
        echo -e "${YELLOW}ADIM 2: SOMUN (Nut)${NC}"
        echo "----------------------------------------------------------------------"
        echo "1. Google Görseller'de arayın:"
        echo "   - 'hex nut'"
        echo "   - 'hexagonal nut'"
        echo "   - 'M8 nut'"
        echo "2. 10 görüntü indirin"
        echo "3. Kayıt yeri: training_data/somun/"
        echo "   Dosya adları: somun_01.jpg, somun_02.jpg, ..."
        echo ""
        echo "✅ İndirdiğinizde ENTER'a basın..."
        read
        
        echo ""
        echo -e "${YELLOW}ADIM 3: RULMAN (Bearing)${NC}"
        echo "----------------------------------------------------------------------"
        echo "1. Google Görseller'de arayın:"
        echo "   - 'ball bearing'"
        echo "   - 'roller bearing'"
        echo "   - 'bearing mechanical'"
        echo "2. 10 görüntü indirin"
        echo "3. Kayıt yeri: training_data/rulman/"
        echo "   Dosya adları: rulman_01.jpg, rulman_02.jpg, ..."
        echo ""
        echo "✅ İndirdiğinizde ENTER'a basın..."
        read
        
        echo ""
        echo -e "${GREEN}🎉 Tebrikler! İlk 30 görüntüyü eklediniz.${NC}"
        echo ""
        echo "Kontrol edelim..."
        python3 check_training_data.py
        ;;
        
    2)
        echo ""
        echo -e "${GREEN}📸 Fotoğraf Çekme Rehberi${NC}"
        echo "======================================================================"
        echo ""
        echo "📷 SETUP ÖNERİLERİ:"
        echo ""
        echo "1. ARKA PLAN:"
        echo "   ✓ Beyaz A4 kağıt (en iyi)"
        echo "   ✓ Düz gri yüzey"
        echo "   ✓ Tek renkli masa örtüsü"
        echo "   ✗ Karışık/desenli arka plan"
        echo ""
        echo "2. IŞIK:"
        echo "   ✓ Gündüz doğal ışık (pencere kenarı)"
        echo "   ✓ LED lamba (yukarıdan, gölge yapmayan)"
        echo "   ✗ Sarı ampul (renk bozar)"
        echo "   ✗ Çok karanlık"
        echo ""
        echo "3. KAMERA (Telefon):"
        echo "   ✓ Parçaya 30-50cm uzaklıktan"
        echo "   ✓ Odaklanmayı bekleyin (tap to focus)"
        echo "   ✓ Sabit tutun (el titremesi olmasın)"
        echo "   ✓ Her parçadan 5-10 fotoğraf (farklı açılar)"
        echo ""
        echo "4. AÇILAR:"
        echo "   - Yukarıdan (90°)"
        echo "   - Yan taraftan (0°)"
        echo "   - 45° açıyla"
        echo "   - Yakın plan"
        echo "   - Uzak plan"
        echo ""
        echo "5. KAYDETME:"
        echo "   - Fotoğrafları bilgisayara aktarın (USB/AirDrop/WhatsApp)"
        echo "   - training_data/[parca_adi]/ klasörüne koyun"
        echo "   - .jpg veya .png formatında"
        echo ""
        echo -e "${YELLOW}💡 İPUCU:${NC} İlk önce 3 parça seçin (vida, somun, rulman)"
        echo "          Her birinden 10 fotoğraf çekin"
        echo "          Toplam: 30 fotoğraf (15-20 dakika)"
        echo ""
        ;;
        
    3)
        echo ""
        echo -e "${GREEN}🔀 Hibrit Yaklaşım (En İyi Sonuç!)${NC}"
        echo "======================================================================"
        echo ""
        echo "ÖNERİLEN PLAN:"
        echo ""
        echo "1. İLK GÜN (2 saat):"
        echo "   - Google'dan her parça için 5 görüntü indirin"
        echo "   - Elinizde parça varsa 5 fotoğraf çekin"
        echo "   - Toplam: 10 görüntü/parça"
        echo "   - 3 parça ile başlayın → 30 görüntü"
        echo ""
        echo "2. İKİNCİ GÜN (1 saat):"
        echo "   - Unsplash.com'dan 5 görüntü daha"
        echo "   - Farklı açılardan 5 fotoğraf daha"
        echo "   - Toplam: 20 görüntü/parça"
        echo ""
        echo "3. İLK HAFTA:"
        echo "   - 6 parçaya çıkarın"
        echo "   - Her parça için 30 görüntü"
        echo "   - İlk model eğitimini yapın"
        echo ""
        echo "4. İLK AY:"
        echo "   - Tüm 10 parça"
        echo "   - Her parça için 100+ görüntü"
        echo "   - Profesyonel model"
        echo ""
        ;;
        
    4)
        echo ""
        echo -e "${BLUE}💡 HIZLI İPUÇLARI${NC}"
        echo "======================================================================"
        echo ""
        echo "🎯 EN HIZLI YÖNTEM:"
        echo "   1. Google Görseller → 'hex bolt' ara"
        echo "   2. 10 görüntü indir (2 dakika)"
        echo "   3. training_data/vida/ klasörüne at"
        echo "   4. Tekrarla: somun, rulman"
        echo "   5. Toplam süre: 10-15 dakika ✅"
        echo ""
        echo "📊 GÖRÜNTÜ SAYILARI:"
        echo "   • Minimum (Test):        10 görüntü/parça  = 100 toplam"
        echo "   • İyi (Kullanılabilir):  50 görüntü/parça  = 500 toplam"
        echo "   • Mükemmel (Pro):       100 görüntü/parça = 1000 toplam"
        echo ""
        echo "🔍 EN İYİ ARAMA TERİMLERİ:"
        echo "   Vida:    'hex bolt', 'machine screw', 'threaded fastener'"
        echo "   Somun:   'hex nut', 'hexagonal nut'"
        echo "   Rulman:  'ball bearing', 'roller bearing'"
        echo "   Dişli:   'gear', 'cogwheel', 'mechanical gear'"
        echo "   Kayış:   'timing belt', 'v-belt'"
        echo "   Piston:  'engine piston', 'piston ring'"
        echo "   Supap:   'valve', 'engine valve'"
        echo "   Krank:   'crankshaft'"
        echo "   Yay:     'spring', 'coil spring', 'compression spring'"
        echo "   Kaynak:  'welded joint', 'weld connection'"
        echo ""
        echo "🌐 ÜCRETSİZ KAYNAKLAR:"
        echo "   • Unsplash.com    (Yüksek kalite, ücretsiz)"
        echo "   • Pexels.com      (Çeşitli)"
        echo "   • Pixabay.com     (Geniş koleksiyon)"
        echo "   • Freepik.com     (Bazı ücretsiz)"
        echo ""
        echo "✅ İYİ GÖRÜNTÜ:"
        echo "   ✓ Tek renkli arka plan"
        echo "   ✓ İyi aydınlatma"
        echo "   ✓ Keskin/net"
        echo "   ✓ 500x500 px veya daha büyük"
        echo ""
        echo "❌ KÖTÜ GÖRÜNTÜ:"
        echo "   ✗ Karışık arka plan"
        echo "   ✗ Bulanık"
        echo "   ✗ Çok küçük (<200x200 px)"
        echo "   ✗ Watermark/logo var"
        echo ""
        ;;
        
    *)
        echo ""
        echo -e "${RED}Geçersiz seçim!${NC}"
        exit 1
        ;;
esac

echo ""
echo "======================================================================"
echo -e "${GREEN}📖 Detaylı Bilgi${NC}"
echo "======================================================================"
echo ""
echo "• Tam rehber: TRAINING_DATA_REHBER.md"
echo "• Durum kontrolü: python check_training_data.py"
echo "• Veri yol haritası: VERİ_TOPLAMA_YOL_HARİTASI.md"
echo ""
echo "======================================================================"
echo -e "${YELLOW}🎯 SONRAKI ADIMLAR${NC}"
echo "======================================================================"
echo ""
echo "1. Görüntüleri ekleyin → training_data/[parca_adi]/"
echo "2. Kontrol edin        → python check_training_data.py"
echo "3. Model eğitin        → python train_model.py --mode train --data_dir ./training_data --epochs 20"
echo "4. Test edin           → streamlit run app.py"
echo ""
echo -e "${GREEN}İyi çalışmalar! 🚀${NC}"
echo ""
